### ISSUE TITLE
Error with Versioning without setuptools-scm installed

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#386]
**Describe the bug**

After pulling the latest develop version and trying to import montepy I got the following error:

``` python
Traceback (most recent call last):
  File "/home/mgale/dev/montepy/montepy/__init__.py", line 28, in <module>
    from . import _version
ImportError: cannot import name '_version' from partially initialized module 'montepy' (most likely due to a circular import) (/home/mgale/dev/montepy/montepy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mgale/miniforge3/lib/python3.10/site-packages/sphinx/config.py", line 358, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/mgale/dev/montepy/doc/source/conf.py", line 18, in <module>
    import montepy
  File "/home/mgale/dev/montepy/montepy/__init__.py", line 35, in <module>
    __version__ = get_version()
  File "/home/mgale/miniforge3/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 158, in get_version
    _version_missing(config)
  File "/home/mgale/miniforge3/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/mgale/dev/montepy/doc/source.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

make: *** [Makefile:20: html] Error 2
```

**To Reproduce**

In a fresh python environment run:

``` shell
git clone ...
cd doc
make html
```

**Version**

3f92bb2

**Additional context**

**Comment by MicahGale** [comment]
`setuptools-scm` is installed.
