### ISSUE TITLE
Parsing of legal MCNP cell definition fails

### ISSUE THREAD

**Issue by dodu94** [idaholab/MontePy#452]
**Some context**
Hi, I work at Fusion For Energy and we are looking at montepy as a possible alternative to substitute numjuggler as our engine for parsing of MCNP input in F4Enix: https://github.com/Fusion4Energy/F4Enix . As you may be aware, in ITER we deal with very long and complex models and unfortunately when I tried to parse some of them I failed almost immediately. I have been struggling to recreate minimum working examples that would show you the bugs I get but I suspect many comes from a way that TopMC (former SuperMC, a CAD2CSG converter) writes the cell definitions.

**Describe the bug**
To start, I isolated a cell definition that is problematic for montepy.

**To Reproduce**

``` python
import montepy
# Read the file
problem = montepy.read_input("extracted_cell.i")
```

**Error Message (if any)**

If an error message was printed please include the entire stacktrace. If it includes any specific values please change or remove them. For example:

``` python
Traceback (most recent call last):
  File "d:\DATA\laghida\Desktop\test_montepy\read.py", line 4, in <module>
    problem = montepy.read_input("extracted_cell.i")
  File "C:\ProgramData\Anaconda3\envs\montepy\lib\site-packages\montepy\input_parser\input_reader.py", line 29, in read_input
    problem.parse_input(replace=replace)
  File "C:\ProgramData\Anaconda3\envs\montepy\lib\site-packages\montepy\mcnp_problem.py", line 286, in parse_input
    raise e
  File "C:\ProgramData\Anaconda3\envs\montepy\lib\site-packages\montepy\mcnp_problem.py", line 271, in parse_input
    obj = obj_parser(input)
  File "C:\ProgramData\Anaconda3\envs\montepy\lib\site-packages\montepy\cell.py", line 88, in __init__
    super().__init__(input, self._parser)
  File "C:\ProgramData\Anaconda3\envs\montepy\lib\site-packages\montepy\mcnp_object.py", line 57, in __init__
    raise ParsingError(
montepy.errors.ParsingError:     extracted_cell.i, line 3

         2| 12817   0    -12887 12892 -12904 12905 -12996
    >    3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
          |                                                       ^ not expected here.
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
         5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
         6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
        10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
There was an error parsing "(".
sly: Syntax error at line 2, token=(

    extracted_cell.i, line 5

         2| 12817   0    -12887 12892 -12904 12905 -12996
         3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
    >    5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
          |       ^ not expected here.
         6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
        10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
There was an error parsing ":".
sly: Syntax error at line 4, token=:

    extracted_cell.i, line 6

         2| 12817   0    -12887 12892 -12904 12905 -12996
         3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
         5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
    >    6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
          |       ^ not expected here.
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
        10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
There was an error parsing ":".
sly: Syntax error at line 5, token=:

    extracted_cell.i, line 10

         2| 12817   0    -12887 12892 -12904 12905 -12996
         3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
         5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
         6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
    >   10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
          |                 ^ not expected here.
There was an error parsing ":".
sly: Syntax error at line 9, token=:

    extracted_cell.i, line 10

         2| 12817   0    -12887 12892 -12904 12905 -12996
         3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
         5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
         6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
    >   10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
          |                            ^ not expected here.
There was an error parsing ":".
sly: Syntax error at line 9, token=:

    extracted_cell.i, line 1

         2| 12817   0    -12887 12892 -12904 12905 -12996
         3|      13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
         4|      :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
         5|      :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
         6|      :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
         7|      :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
         8|      :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
         9|      :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
        10|         U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit
The input ended prematurely.
sly: Parse error in input. EOF
```

**MCNP input file snippet**

If applicable, please include a small section of the input file you were working on. If it includes any specific values please change or remove them. For example:

```
A title
12817   0    -12887 12892 -12904 12905 -12996
     13016 ( -13036:13306:12989:-13307:-12997:13033 )( -13368:12853:13034
     :-13036 )( -13368:13305:-13039:-13000:12986:-13308:13036 )( -13036
     :13305:12853:13034:13368 )( 13305:-13000:-13039:13368:13036 )( -13036
     :12853:13034:-13305 )( -13305:-13039:-13000:12986:13304:13368
     :13036 )( -13313:12709:12984:13320:-13032:-13005 )( -13313:12709
     :13320:-13013:-13060:13005 )( -12867:-13012:13320:13060:13005
     :-13299 )( -13297:13060:-12866:13320:-13013:13012 )
        U=4 IMP:N=1.0  IMP:P=1.0             $void reach face limit

12709       KZ   -1323.873913042123600  0.119622364181436  1
12853      GQ   0.037328941398423  0.962671058601577  1.000000000000000
         -0.379133177300517  0.0  0.0  -2.009352707108760
         10.204043399318643  498.400000000012260  62127.190000002243000
12866      CZ   359.800000000000010
12867      CZ   359.579283346402010
12887      PX   363.000000000000000
12892      PX   293.500000000000000
12904      PY   65.375000000000000
12905      PY   30.250000000000000
12984      PZ   -238.500000000000400
12986      PZ   -240.000000000006340
12989      PZ   -241.599999999996530
12996      PZ   -248.125000000000000
12997      PZ   -248.400000000006230
13000      PZ   -250.000000000006340
13005      PZ   -251.500000000000000
13012      PZ   -263.649999999999980
13013      PZ   -264.500000000000000
13016      PZ   -288.750000000000000
13032      P    0.981158019180059  0.193206991070882  0.0  364.000000000073780
13033      P    0.981158019180181  0.193206991070259  0.0  361.500000000266310
13034      P    0.981158019180181  0.193206991070259  0.0  361.100000000266330
13036      P    0.981158019180181  0.193206991070259  0.0  360.170000000266730
13039      P    0.981158019180181  0.193206991070259  0.0  356.500000000265970
13060      P    0.973058285351936  0.230559262030288  0.0  360.470283345967740
13297      P    0.230217044746210  -0.971613982656261  0.054464493159870
         -9.358447009845865
13299      P    0.225012501958025  -0.949648595376152  0.218029629322925
         -51.841295556157796
13304      P    0.193206991070259  -0.981158019180181  0.0  5.999999999908238
13305      P    0.193206991070259  -0.981158019180181  0.0  5.199999999937588
13306      P    0.193206991070259  -0.981158019180181  0.0  4.449999999908210
13307      P    0.193206991070259  -0.981158019180181  0.0  -0.650000000091694
13308      P    0.193206991070259  -0.981158019180181  0.0  -1.300000000063440
13313      P    0.193206991070882  -0.981158019180059  0.0  -7.499999999961318
13320      P    0.173648177667279  -0.984807753012147  0.0  -0.499999999999913
13368      P    -0.193158843309286  0.980913511662501  0.022323617300079
         -10.574231190202608

MODE N
```

**Version**

 - Version 0.3.0

**Comment by MicahGale** [comment]
I was able to confirm that this is only #355, and not another bug going on. So I'm going to merge this with that issue, and you can add any extra context there.

Thank you for your bug report, and using version 0.3.0 so soon. 😄

**Comment by MicahGale** [comment]
I just saw you are looking into converting to montepy from NumJuggler. If you have any more questions feel free to email me directly.

**Comment by dodu94** [comment]
Thanks! will do for sure in case there is any need.
