### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by marco-de-pietri** [idaholab/MontePy#453]
**Describe the bug**

Hello, I am encountering a bug when parsing a cell - probably related to some inline comment

**To Reproduce**

``` python
problem = montepy.read_input("foo.imcnp")
```

**Error Message (if any)**

``` python
/home/marco/miniforge3/lib/python3.10/site-packages/montepy/input_parser/input_syntax_reader.py:184: LineOverRunWarning: The line:           IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 500261
 exceeded the allowed line length of: 128 for MCNP (6, 2, 0)
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/c/Users/marco/OneDrive - UNED/01_WORK/47_ANTENNA/03_FULL_MODEL_PROC/03_CLEAN_SURFACES/test.py", line 3, in <module>
    problem = montepy.read_input("test")
  File "/home/marco/miniforge3/lib/python3.10/site-packages/montepy/input_parser/input_reader.py", line 29, in read_input
    problem.parse_input(replace=replace)
  File "/home/marco/miniforge3/lib/python3.10/site-packages/montepy/mcnp_problem.py", line 286, in parse_input
    raise e
  File "/home/marco/miniforge3/lib/python3.10/site-packages/montepy/mcnp_problem.py", line 271, in parse_input
    obj = obj_parser(input)
  File "/home/marco/miniforge3/lib/python3.10/site-packages/montepy/cell.py", line 88, in __init__
    super().__init__(input, self._parser)
  File "/home/marco/miniforge3/lib/python3.10/site-packages/montepy/mcnp_object.py", line 57, in __init__
    raise ParsingError(
montepy.errors.ParsingError:     test, line 21

    >   21| 500330   0   ( -501375 501376 -501516 501733 -501830 501856 )((505380
          |                                                              ^ not expected here.
        22|           :504759:-503268:-505404:-503960:503267))((-503778:-505173:503269
        23|           :503777:505380:-503267))((-503778:505380:-503268:503960:-505173
        24|           :503267))((504763:-503775:503263:501866:505381:-503266:-505382))
        25|           IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 50
There was an error parsing "(".
sly: Syntax error at line 1, token=(

    test, line 25

        21| 500330   0   ( -501375 501376 -501516 501733 -501830 501856 )((505380
        22|           :504759:-503268:-505404:-503960:503267))((-503778:-505173:503269
        23|           :503777:505380:-503267))((-503778:505380:-503268:503960:-505173
        24|           :503267))((504763:-503775:503263:501866:505381:-503266:-505382))
    >   25|           IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 50
          |                          ^ not expected here.
There was an error parsing ":".
sly: Syntax error at line 5, token=:

    test, line 25

        21| 500330   0   ( -501375 501376 -501516 501733 -501830 501856 )((505380
        22|           :504759:-503268:-505404:-503960:503267))((-503778:-505173:503269
        23|           :503777:505380:-503267))((-503778:505380:-503268:503960:-505173
        24|           :503267))((504763:-503775:503263:501866:505381:-503266:-505382))
    >   25|           IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 50
          |                                   ^ not expected here.
There was an error parsing "=".
sly: Syntax error at line 5, token==

    test, line 20

        21| 500330   0   ( -501375 501376 -501516 501733 -501830 501856 )((505380
        22|           :504759:-503268:-505404:-503960:503267))((-503778:-505173:503269
        23|           :503777:505380:-503267))((-503778:505380:-503268:503960:-505173
        24|           :503267))((504763:-503775:503263:501866:505381:-503266:-505382))
        25|           IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 50
The input ended prematurely.
sly: Parse error in input. EOF

```

**MCNP input file snippet**

```
Test Model
C Lost particle check model
C Sphere
1  0  -1
       IMP:N=1.0  IMP:P=1.0 FILL= 70
2  0  1 -2
       IMP:N=1.0  IMP:P=1.0
C outside
3  0   2
       IMP:N=0.0  IMP:P=0.0
C ======================================================================
500330   0   ( -501375 501376 -501516 501733 -501830 501856 )((505380
          :504759:-503268:-505404:-503960:503267))((-503778:-505173:503269
          :503777:505380:-503267))((-503778:505380:-503268:503960:-505173
          :503267))((504763:-503775:503263:501866:505381:-503266:-505382))
          IMP:N=1.0  IMP:P=1.0  U=70            $void reach face limitpos:(562, -86, 395) ~ (613, 0, 447.5) Int cells: 500259 500261
```

**Version**

 - Version 0.3.0

**Comment by dodu94** [comment]
I guess we had the same idea today :D #453

**Comment by MicahGale** [comment]
This sounds very similar to #355. I'll check if that is the issue or if there is something else going on as well.

**Comment by MicahGale** [comment]
Ok I did confirm this is only #355; I confirmed this by adding spaces between parentheses groups. I'm going to close this issue as a duplicate.

Thank you for your bug report, and feel free to add more context to #355.

Also I'm surprised you both installed 0.3.0 in less than 24 hours. 😄

**Comment by marco-de-pietri** [comment]
clear cases of experiment friday 😄! thanks for the feedback
