### ISSUE TITLE
Improve Isotope Instantiation

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#505]
**Is your feature request related to a problem? Please describe.**

"I'm always frustrated when" I want to instantiate an `Isotope`, but have to remember that it lives at `montepy.data_inputs.isotope.Isotope`. It should be a top-level object.

Also annoying is that the representation uses the "Element-Z" convention, but instantiation has to use ZAID.

**Example**

```python
>>> montepy.data_inputs.isotope.Isotope("1001.00c")
Isotope('H-1.00c')

>>> Isotope('H-1.00c')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Isotope' is not defined

>>> montepy.data_inputs.isotope.Isotope("H-1.00c")
Traceback (most recent call last):
  File "montepy/data_inputs/isotope.py", line 34, in __init__
    int(parts[0])
ValueError: invalid literal for int() with base 10: 'H-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "montepy/data_inputs/isotope.py", line 36, in __init__
    raise ValueError(f"ZAID: {ZAID} could not be parsed as a valid isotope")
ValueError: ZAID: H-1.00c could not be parsed as a valid isotope

```

**Describe the solution you'd like**
 * Import the `Isotope` class into the top-level namespace, in _montepy/__init__.py_
 * Allow instantiation from, e.g., `montepy.Isotope("H-1.00c")`, `montepy.Isotope("H1.01c")`, etc.

**Additional context**
[Someone](https://github.com/tjlaboss) changed the `repr` in #473, but didn't bother to update `__init__` accordingly.

**Comment by MicahGale** [comment]
See the initial function over on `mat_redesign`. Also `get_from_fancy_name`.

**Comment by MicahGale** [comment]
Side note: `montepy.particle.Particle` is annoying. I think we need to make basically everything a top level object. At the very least `module.Class` for `particle.Particle` is really annoying.

**Comment by tjlaboss** [comment]
Yes.
