### ISSUE TITLE
Make `Material.is_atom_fraction` settable

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#511]
``` python
Traceback (most recent call last):
  File "/home/mgale/dev/montepy/gen_big_model.py", line 12, in <module>
    gen_mega_mat()
  File "/home/mgale/dev/montepy/gen_big_model.py", line 6, in gen_mega_mat
    mat.is_atom_fraction = True
AttributeError: can't set attribute 'is_atom_fraction'
```

**Comment by MicahGale** [comment]
Related to #84
