### ISSUE TITLE
Memory leaks with copy.deepcopy

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#514]
So I was making a lot of copies of a cell with `copy.deepcopy` and it went very badly

``` python
import montepy
problem = montepy.read_input("foo")
for i in range(1_000):
    new_cell = copy.deepcopy(problem.cells[1])
    ...
```

This script kept crashing. It got really slow around `i==11` and was using over 3GB of RAM!

This is very telling for when I ran ctrl-C:

``` python
^CTraceback (most recent call last):
  File "/home/mgale/dev/montepy/mod_big_model.py", line 11, in <module>
    new_cell = copy.deepcopy(base_cell)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/mgale/mambaforge/lib/python3.10/copy.py", line 264, in _reconstruct
    args = (deepcopy(arg, memo) for arg in args)
KeyboardInterrupt
```

We have a copy recursion problem.

**Comment by MicahGale** [comment]
I think we need `__weakref__` for `self._problem`

**Comment by MicahGale** [comment]
Also to implement #469

**Comment by MicahGale** [comment]
Temporary workaround:

1. Unlink problem 
2. Copy object
3. relink object

``` python
problem =...
base_cell = problem.cells[1]
base_cell._problem = None
new_cell = copy.deepcopy(base_cell)
base_cell.link_to_problem(problem)
... # make more copies if needed, etc
new_cell.link_to_problem(problem)
```

This still isn't super memory efficient, but it works well enough.

**Comment by MicahGale** [comment]
I have a hunch that this is causing #463.
